### PR TITLE
[myank] Fix insertZerothMeasure and allow line yank for anacruses

### LINKED ISSUE #83: [myank] Pickups do not work
When I try to use e.g. `cat test.krn | myank -l 2-10` on a file with a pickup before the first measure the command will fail and actually output the whole kern data and does not yank anything.

#### test.krn

```
**kern
4e
=1
4a
4g
4f
4e
=2
2d
4e
4b
=3
4cc
4cc
4b
4b
=4
1a;
==
*-
```

#### Expected output with `myank -l 2-10`

```
**kern
4e
=1
4a
4g
4f
4e
=2
2d
4e
*-
```

I tried to debug this, but I don't yet understand fully the logic of `MeasureInfo` and where it does get hydrated. It looks like in `Tool_myank::processFile` the `expandMeasureOutList` function does not assign anything to `m_measureOutList`. Would it make sense to add an additional `MeasureInfo` element that contains all notes before the first bar number (e.g. as `NUMBER = 0` or `NUMBER = -1`) at the beginning of the vector?

### PR DESCRIPTION
**Pull request by WolfgangDrescher**
Closes #83

### CODE REVIEW

**Comment by WolfgangDrescher** [comment]
Currently it is not possible to myank with `-l` option, if a kern file does not have any measure numbers (e.g. https://github.com/craigsapp/bach-370-chorales/blob/94734465d7e71857a9233d04f3431c72c461ef0e/kern/chor087.krn)

`myank -I -l 22-39` will throw `Error: There are no measure numbers present in the data` although it is not important for a `myank` with the lines option enables whether there are measure numbers or not.

My current approach to this is to change in `Tool_myank::insertZerothMeasure`:

```cpp
if (stopline < 0 && !getBoolean("lines")) {
```

and in `Tool_myank::expandMeasureOutList`

```cpp
if (maxmeasure <= 0 && !getBoolean("lines")) {
```

But it's not working yet…

**Comment by craigsapp** [comment]
What is the status of this PR?  I see "But it's not working yet…", so I should be ignoring it for now? :-)

**Comment by WolfgangDrescher** [comment]
It's actually another problem than the one I fixed in this PR. Should have opened another issue or PR. However, I managed to find a way to fix the problem with `myank -l` when there are no measure numbers encoded.

If in `Tool_myank::getMeasureStartStop` the `measurelist` vector does not have any elements and the `-l` option is used, it will add a measure to `measurelist` with the whole kern data where `start` is 0 and `stop` is `dataend`.

It's ready for review now.

**Comment by WolfgangDrescher** [comment]
Is there anything I need to change in this PR? From my side, it's ready to merge.

**Pull request merged**
